"use client";

import { useEffect, useRef, useState } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useGSAP } from "@gsap/react";

if (typeof window !== "undefined") {
  gsap.registerPlugin(ScrollTrigger, useGSAP);
}

interface ScrollVideoProps {
  src?: string;
  triggerRef: React.RefObject<HTMLElement | null>;
  className?: string;
}

export function ScrollVideo({ triggerRef, className }: ScrollVideoProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [imagesLoaded, setImagesLoaded] = useState(false);
  const frameCount = 404; // Exact number of frames generated by FFmpeg
  
  const imagesRef = useRef<HTMLImageElement[]>([]);
  const playhead = useRef({ frame: 1 });

  // Preload all frames into RAM
  useEffect(() => {
    let loadedCount = 0;
    const imgs: HTMLImageElement[] = [];

    for (let i = 1; i <= frameCount; i++) {
      const img = new Image();
      const frameNumber = i.toString().padStart(4, "0");
      img.src = `/frames/frame_${frameNumber}.jpg`;
      img.onload = () => {
        loadedCount++;
        // Allow starting the animation even if a few are missing, but ideally wait for all
        if (loadedCount >= frameCount * 0.8) {
          setImagesLoaded(true);
        }
      };
      imgs.push(img);
    }
    
    imagesRef.current = imgs;
  }, []);

  // Initial draw
  useEffect(() => {
    if (!imagesLoaded) return;
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    
    const firstValidImg = imagesRef.current.find(img => img && img.complete && img.naturalWidth > 0);
    if (!firstValidImg) return;
    
    canvas.width = firstValidImg.naturalWidth || 1280;
    canvas.height = firstValidImg.naturalHeight || 720;
    
    ctx.drawImage(firstValidImg, 0, 0, canvas.width, canvas.height);
    ScrollTrigger.refresh();
  }, [imagesLoaded]);

  // GSAP ScrollTrigger for Canvas drawing
  useGSAP(() => {
    if (!imagesLoaded || !triggerRef.current || !canvasRef.current) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext("2d");

    const render = () => {
      if (!ctx || !imagesRef.current.length) return;
      const frameIndex = Math.min(
        frameCount - 1, 
        Math.max(0, Math.round(playhead.current.frame) - 1)
      );
      const img = imagesRef.current[frameIndex];
      // Only draw if image is actually loaded
      if (img && img.complete && img.naturalWidth > 0) {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
      }
    };

    const scrollAnim = gsap.to(playhead.current, {
      frame: frameCount,
      snap: "frame",
      ease: "none",
      scrollTrigger: {
        trigger: triggerRef.current,
        start: "top 112px", // Account for the 112px header height so animation starts on pixel 1
        end: "bottom bottom", // Finish animation exactly at the end of the container
        scrub: 0.1, // Smooth fast scrubbing
      },
      onUpdate: render,
    });

    return () => {
      scrollAnim.kill();
    };
  }, [imagesLoaded, triggerRef]);

  return (
    <canvas
      ref={canvasRef}
      className={className}
    />
  );
}
