"use client";

import { useEffect, useRef, useState } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useGSAP } from "@gsap/react";

if (typeof window !== "undefined") {
  gsap.registerPlugin(ScrollTrigger, useGSAP);
}

interface ScrollVideoProps {
  src?: string;
  triggerRef: React.RefObject<HTMLElement | null>;
  className?: string;
}

export function ScrollVideo({ triggerRef, className }: ScrollVideoProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [imagesLoaded, setImagesLoaded] = useState(false);
  const frameCount = 404; // Exact number of frames generated by FFmpeg
  
  const imagesRef = useRef<HTMLImageElement[]>([]);
  const playhead = useRef({ frame: 1 });

  // Preload frames in batches to avoid network congestion (especially in Opera)
  useEffect(() => {
    const batchSize = 10;
    imagesRef.current = new Array(frameCount);

    const loadBatch = (start: number) => {
      if (start > frameCount) return;
      
      let loadedInBatch = 0;
      const end = Math.min(start + batchSize - 1, frameCount);
      const totalToLoad = end - start + 1;
      
      for (let i = start; i <= end; i++) {
        const img = new Image();
        const frameNumber = i.toString().padStart(4, "0");
        img.src = `/frames/frame_${frameNumber}.jpg`;
        
        img.onload = () => {
          imagesRef.current[i - 1] = img;
          loadedInBatch++;
          
          // Allow showing the first frame immediately!
          if (i === 1) {
            setImagesLoaded(true);
          }
          
          // When current batch finishes, start the next one
          if (loadedInBatch === totalToLoad) {
             loadBatch(end + 1);
          }
        };

        // Fallback in case a frame fails to load, so it doesn't halt the whole batch
        img.onerror = () => {
          loadedInBatch++;
          if (loadedInBatch === totalToLoad) {
             loadBatch(end + 1);
          }
        };
      }
    };
    
    // Start loading the first batch
    loadBatch(1);
  }, []);

  // GSAP ScrollTrigger for Canvas drawing
  useGSAP(() => {
    if (!imagesLoaded || !triggerRef.current || !canvasRef.current) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext("2d");

    const render = () => {
      if (!ctx || !imagesRef.current.length) return;
      const frameIndex = Math.min(
        frameCount - 1, 
        Math.max(0, Math.round(playhead.current.frame) - 1)
      );
      
      // Find the closest loaded frame looking backwards
      let imgToDraw = null;
      for (let i = frameIndex; i >= 0; i--) {
        const img = imagesRef.current[i];
        if (img && img.complete && img.naturalWidth > 0) {
           imgToDraw = img;
           break;
        }
      }

      if (imgToDraw) {
        // Only set canvas dimensions once based on the first drawn image
        if (canvas.width !== imgToDraw.naturalWidth && imgToDraw.naturalWidth > 0) {
          canvas.width = imgToDraw.naturalWidth;
          canvas.height = imgToDraw.naturalHeight;
        }
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        ctx.drawImage(imgToDraw, 0, 0, canvas.width, canvas.height);
      }
    };

    // Force an initial render as soon as useGSAP runs
    render();

    const scrollAnim = gsap.to(playhead.current, {
      frame: frameCount,
      snap: "frame",
      ease: "none",
      scrollTrigger: {
        trigger: triggerRef.current,
        start: "top 112px",
        end: "bottom bottom",
        scrub: 0.1,
      },
      onUpdate: render,
    });

    return () => {
      scrollAnim.kill();
    };
  }, [imagesLoaded, triggerRef]);

  return (
    <canvas
      ref={canvasRef}
      className={className}
    />
  );
}
